# This will enforce that ONLY traffic that is TLS is allowed between proxies
apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: "default"
  namespace: "istio-system"
spec:
  mtls:
    # mode: STRICT # strick mTLS does not allow http
    mode: PERMISSIVE # still upgrade to mTLS where istio can, but still allow non-mtls
